### ISSUE TITLE
SS4 update might be interesting?

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-form-extras#7]
Especially the FrontEndUploadField could be interesting, as the SS4 UploadField is not suitable/usable for front-end purposes. Any chance parts of this module will be updated?

**Comment by lekoala** [comment]
well, i don't know yet. this module is a bit of mixed things based on various websites I had to work on.

currently, I'm working on this
https://github.com/lekoala/silverstripe-base

If you want a file uploader for the frontend, i highly recommend using filepond which is just amazing
https://github.com/lekoala/silverstripe-base/blob/master/code/Forms/FilePondField.php

This module is pretty much wip, but it should be easy enough to copy the form fields you like :-)
